# Generated by Django 4.1.6 on 2023-02-15 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_customer_driver'),
        ('inventory', '0006_service_delete_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PickUpStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='delivery.location')),
            ],
        ),
        migrations.CreateModel(
            name='UserPickUpStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='delivery.pickupstation')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('OFD', 'Out For Delivery'), ('DL', 'Delivered')], default='PD', max_length=3, verbose_name='status')),
                ('driver', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.driver')),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory.order')),
                ('station', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='delivery.userpickupstation')),
            ],
        ),
    ]
