# Generated by Django 4.1.6 on 2023-02-22 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0014_alter_cartitem_unique_together_alter_cart_items_and_more'),
        ('delivery', '0003_alter_delivery_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateTimeField(auto_now=True, verbose_name='shipped_date')),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('OFD', 'Out For Delivery'), ('DL', 'Delivered')], default='PD', max_length=3, verbose_name='status')),
                ('driver', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory.order')),
                ('station', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='delivery.userpickupstation')),
            ],
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
