# Generated by Django 4.1.6 on 2023-02-21 13:33

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='KES', max_digits=10, verbose_name='total amount'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='KES', max_digits=10),
        ),
    ]
