# Generated by Django 4.1.6 on 2023-02-15 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='installation_cost',
        ),
    ]
