# Generated by Django 4.1.6 on 2023-02-15 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_product_installation_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='installation_cost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installation_costs', to='inventory.category'),
        ),
    ]
