# Generated by Django 4.1.6 on 2023-02-15 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_installation_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='installation_cost',
        ),
    ]
