# Generated by Django 4.1.6 on 2023-02-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_service_delete_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='installation_cost',
        ),
    ]
