# Generated by Django 4.1.6 on 2023-02-21 13:33

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_product_installation_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.AlterField(
            model_name='category',
            name='installation_cost',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='KES', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='KES', max_digits=10),
        ),
    ]
