# Generated by Django 4.1.6 on 2023-02-21 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_cartitem_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='inventory.CartItem', to='inventory.product'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
