# Generated by Django 4.1.6 on 2023-02-21 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_cartitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.order'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('product', 'order')},
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
