# Generated by Django 4.1.6 on 2023-02-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_cartitem_unique_together_alter_cart_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
