# Generated by Django 4.1.6 on 2023-02-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_service_description_alter_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default='Pending Payment', max_length=10),
        ),
    ]
